
server.port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio_cadastro_projeto
    username: desafio_cadastro_projeto
    password: desafio_cadastro_projeto
    schema-username: desafio_cadastro_projeto
    schema-password: desafio_cadastro_projeto
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE